### ISSUE TITLE
Add Zulip to Communication Section

### ISSUE THREAD

**Issue by armaanahluwalia** [jitenbansal/awesome-free-and-essential-products-for-startups#1]
Should add [Zulip Chat](http://www.zulipchat.com) to the communication section. Unlike Slack its free and open source. Has 11000 stars on Github.

Full Disclosure: I'm a contributor : )

**Comment by jitenbansal** [comment]
Updated. Thanks for your contribution.

**Comment by armaanahluwalia** [comment]
No problem. Thanks for creating this!
